# Generated by Django 6.0.2 on 2026-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
