# Generated by Django 6.0.2 on 2026-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_siciallink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SicialLink',
            new_name='SocialLink',
        ),
    ]
